### ISSUE TITLE
Protótipo do Projeto (Wireframes)

### ISSUE THREAD

**Issue by MrNullus** [Victoreisdavid/FiscalizaJa#4]
Desde já achei massa o projeto, por acaso possui algum protótipo no Figma, por exemplo? Já que mexo com isso posso ajudar, já até pensei em algumas coisas para a UI

**Comment by Victoreisdavid** [comment]
Bom dia, MrNullus! Atualmente não tenho nenhum wireframe da UI no Figma, se quiser dar sugestões sobre como melhorar a UI, pode ficar a vontade! pode enviar por aqui o protótipo ou no servidor do Discord, mandei o link lá no seu comentário na issue #2 !

**Comment by MrNullus** [comment]
Certo, obrigado!
